services:
  db:
    image: postgres:16
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: on-failure

  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./media:/app/media
    restart: on-failure
    command: >
      sh -c "python manage.py migrate &&
             python manage.py seed_data 2>/dev/null;
             gunicorn configs.wsgi:application --bind 0.0.0.0:8000 --workers 3"

  celery:
    build: .
    env_file:
      - .env
    depends_on:
      - redis
      - db
    command: celery -A configs worker -l info
    restart: on-failure

  celery-beat:
    build: .
    env_file:
      - .env
    depends_on:
      - redis
      - db
    command: celery -A configs beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    restart: on-failure

volumes:
  postgres_data:
